version: '2.4'

services:
  postgres:
    restart: always
    container_name: Keycloak_Postgres
    image: postgres:14.5
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - 127.0.0.1:5432:5432

  keycloak:
    restart: always
    platform: linux/amd64
    volumes:
      - ./providers/:/opt/jboss/keycloak/providers:rw
#      - ./themes/:/opt/jboss/keycloak/themes/:rw
    depends_on:
      - postgres
    container_name: Keycloak_Server
    image: quay.io/keycloak/keycloak:19.0.2-legacy
    env_file:
      - .env
    ports:
      - 127.0.0.1:8080:8080
    command:
      - "-b 0.0.0.0"
      - ${KEYCLOAK_ADDITIONAL_OPTS}
